
branches:
  only:
    - master

sudo: required
dist: trusty
language: c++
compiler: gcc
notifications:
  - email: false

before_script:
  - apt-get install -qq bison flex
  - bison --version
  - flex --version

script: make
