
branches:
  only:
    - master

addons:
  apt:
    packages:
      - bison
      - flex

language: c++

compiler: gcc

notifications:
  - email: false

before_script:
  - bison --version
  - flex --version

script: make
